INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}../include)

IF(MINGW)
  SET(EXTRA_LIBS mingw32 shlwapi)
ENDIF()

FILE(GLOB TEST_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
FOREACH(TEST_FILENAME ${TEST_SOURCES})
  GET_FILENAME_COMPONENT(TEST_NAME ${TEST_FILENAME} NAME_WE)
  ADD_EXECUTABLE(${TEST_NAME} ${TEST_FILENAME})

  TARGET_INCLUDE_DIRECTORIES(
    ${TEST_NAME}
    PUBLIC
      ${CMAKE_CURRENT_SOURCE_DIR}/../include
  )

  TARGET_COMPILE_FEATURES(
    ${TEST_NAME}
    PUBLIC
      cxx_std_17
  )

  IF(MINGW)
    TARGET_COMPILE_OPTIONS(
      ${TEST_NAME}
      PRIVATE
        -static -static-libgcc -static-libstdc++
    )
  ENDIF()

  TARGET_LINK_LIBRARIES(
    ${TEST_NAME}
    PeeloGlob
    ${EXTRA_LIBS}
  )

  ADD_TEST(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
ENDFOREACH()
